version: "2.4"

services:
    node:
        ports:
            - "8080:3000"
        networks:
            - webnet
        build:
            context: ./
            dockerfile: Dockerfile
        platform: linux
networks:
    webnet: