version: '3.4'

services:
  demoapp:
    image: demoapp
    build:
      context: ./DemoApp
      dockerfile: Dockerfile
    container_name: demoapp
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "80"
    networks:
      - web
      - db
  sql:
    ports:
      - "1433:1433"
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
    container_name: demoapp_sql
    networks:
      db:
        aliases:
          - sql

networks:
  web:
  db: